config/routes.rb
InstructMe::Application.routes.draw do

  resources :instructions, :only => %w(new create show edit update)

  root :to => "instructions#new"

end

app/models/command.rb
class Command < ActiveRecord::Base

  acts_as_list :scope => :step_id

  ### associations ###
  belongs_to :step

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base

  ### normalizations ###
  normalize_attributes :title

  ### validations ###
  validates :title, :presence => true

  ### associations ###
  has_many :steps, :order => 'position'
  accepts_nested_attributes_for :steps, :allow_destroy => true

  ### callbacks ###
  after_initialize { steps.build if steps.empty? }

  def add_step
    false
  end

  def add_step=(val)
    steps.build if val == '1'
  end

end

app/models/step.rb
class Step < ActiveRecord::Base

  acts_as_list :scope => :instruction_id

  ### associations ###
  belongs_to :instruction
  has_many :commands, :order => 'position'
  accepts_nested_attributes_for :commands, :allow_destroy => true

  ### callbacks ###
  after_initialize { commands.build if commands.empty? }

  def add_command
    false
  end

  def add_command=(val)
    commands.build if val == '1'
  end

end

app/models/user.rb
class User

  def initialize(id)
    @id = id.to_s
  end

  def instructions
    Instruction.where(:user_id => @id)
  end

  # def build_instruction(attrs = {})
  #   Instruction.new(attrs.merge(:user_id => @id))
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_filter :set_current_user

  private

  def set_current_user
    @current_user = User.new(request.session_options[:id])
  end

end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController

  before_filter :build_instruction, :only => %w(new)
  before_filter :find_instruction, :only => %w(show edit update)

  def new
  end

  def create
    session[:new_instruction_attrs] = params[:instruction]
    if params[:save] # save button pressed
      build_instruction
      if @instruction.save
        session[:new_instruction_attrs] = nil
        redirect_to instruction_url(@instruction)
      else
        render :new
      end
    else
      redirect_to root_url
    end
  end

  def show
  end

  def edit
  end

  def update
    if @instruction.update_attributes(params[:instruction])
      if params[:view] # view button pressed
        redirect_to instruction_url(@instruction)
      else
        redirect_to edit_instruction_url(@instruction)
      end
    else
      render :edit
    end
  end

  private

  def build_instruction
    @instruction = @current_user.instructions.build(session[:new_instruction_attrs])
  end

  def find_instruction
    @instruction = @current_user.instructions.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def css_class_string_for_listable(name, position, total_items)
    [name, "#{name}_#{position}"].tap do |ary|
      ary << "last_#{name}" if position == total_items
    end.join(' ')
  end

end

app/views/instructions/_form.html.haml
= simple_form_for @instruction do |f|
  %h2 Create Instructions
  .title
    = f.input :title
  .steps
    - step_nbr = 0
    - nbr_of_steps = @instruction.steps.size
    = f.simple_fields_for :steps do |s_f|
      - step_nbr += 1
      %div{:class => css_class_string_for_listable('step', step_nbr, nbr_of_steps)}
        .step_header
          %h3= "Step #{step_nbr}"
          - if nbr_of_steps > 1
            .remove_step= s_f.input :_destroy, :as => :boolean, :label => 'remove'
          .clear
        .step_body
          = s_f.input :description, :wrapper_html => {:class => 'description'}, :input_html => {:rows => 2, :cols => 60}
          
          .commands
            %label Commands
            - cmd_nbr = 0
            - nbr_of_cmds = s_f.object.commands.size
            = s_f.simple_fields_for :commands do |c_f|
              - cmd_nbr += 1
              %div{:class => css_class_string_for_listable('command', cmd_nbr, nbr_of_cmds)}
                = c_f.input :body, :as => 'string', :label => false
                - if nbr_of_cmds > 1
                  %span.remove_command= c_f.input :_destroy, :as => :boolean, :label => 'remove'
            .add_command= s_f.input :add_command, :as => :boolean, :label => 'add'
          
    .add_step= f.input :add_step, :as => :boolean, :label => 'add step'
  .form_footer
    - if @instruction.new_record?
      %button{:type => 'submit', :name => 'save'} Save and view instructions
    - else
      %button{:type => 'submit', :name => 'view'} View instructions

app/views/instructions/edit.html.haml
= render 'form'

app/views/instructions/new.html.haml
= simple_form_for @instruction, :url => root_path do |f|
  %h2 Create Instructions
  .title
    = f.input :title
  .steps
    - step_nbr = 0
    - nbr_of_steps = @instruction.steps.size
    = f.simple_fields_for :steps do |s_f|
      - step_nbr += 1
      %div{:class => css_class_string_for_listable('step', step_nbr, nbr_of_steps)}
        .step_header
          %h3= "Step #{step_nbr}"
          - if nbr_of_steps > 1
            .remove_step= s_f.input :_destroy, :as => :boolean, :label => 'remove'
          .clear
        .step_body
          = s_f.input :description, :wrapper_html => {:class => 'description'}, :input_html => {:rows => 2, :cols => 60}
          
          .commands
            %label Commands
            - cmd_nbr = 0
            - nbr_of_cmds = s_f.object.commands.size
            = s_f.simple_fields_for :commands do |c_f|
              - cmd_nbr += 1
              %div{:class => css_class_string_for_listable('command', cmd_nbr, nbr_of_cmds)}
                = c_f.input :body, :as => 'string', :label => false
                - if nbr_of_cmds > 1
                  %span.remove_command= c_f.input :_destroy, :as => :boolean, :label => 'remove'
            .add_command= s_f.input :add_command, :as => :boolean, :label => 'add'
          
    .add_step= f.input :add_step, :as => :boolean, :label => 'add step'
  .form_footer
    %button{:type => 'submit', :name => 'save'} Save and view instructions

app/views/instructions/show.html.haml
.instructions
  %h2= @instruction.title
  %p= link_to "Edit these instructions", edit_instruction_path(@instruction)

  %ul.steps
    - @instruction.steps.each do |step|
      %li.step{:class => "step_#{step.position}"}
        %h5= step.description
        %ul.commands
          - step.commands.each do |command|
            %li.command{:class => "command_#{command.position}"}
              %code= command.body

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Instruct Me
    %meta{:name => "viewport", :content => "user-scalable=no, width=device-width"}
    = csrf_meta_tag
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = javascript_include_tag :defaults, 'nested_form'
  %body
    #header
      %h1 Instruct Me
    #content
      = yield
    #footer
      .col1
        %p
          Built by
          = link_to "Austin Schneider", "http://austinschneider.com"
          using
          = succeed '.' do
            = link_to "Ruby on Rails", "http://rubyonrails.org"
        
      .col2
        %p
          This application is open source.
          = succeed '.' do
            = link_to "View the project", "http://github.com/soccer022483/instruct_me"
            
        %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post"}
          = hidden_field_tag "cmd", "_s-xclick"
          = hidden_field_tag "hosted_button_id","HNV3UNAA3S9XU"
          = image_submit_tag "https://www.paypal.com/en_US/i/btn/btn_donate_SM.gif", :name => "submit", :alt => "PayPal - The safer, easier way to pay online!", :border => 0
          = image_tag "https://www.paypal.com/en_US/i/scr/pixel.gif", :border => 0, :width => 1, :height => 1, :alt => ""
      .clear